export interface Product {
  id: number
  name: string
  brand: string
  price: number
  oldPrice?: number
  category: string
  subcategory: string
  gender: "women" | "men" | "unisex"
  sizes: string[]
  colors: string[]
  images: string[]
  description: string
  composition: string
  care: string
  tryOnImage?: string
  tryOnCategory?: "auto" | "tops" | "bottoms" | "one-pieces"
  tryOnGarmentPhotoType?: "auto" | "flat-lay" | "model"
  isNew?: boolean
  isSale?: boolean
}

export const products: Product[] = [
  {
    id: 1,
    name: "Пальто прямого кроя",
    brand: "ZARINA",
    price: 12990,
    oldPrice: 18990,
    category: "Одежда",
    subcategory: "Пальто",
    gender: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Бежевый", "Чёрный"],
    images: ["/beige-wool-coat-women-elegant.jpg"],
    description:
      "Элегантное пальто прямого кроя из мягкой шерстяной ткани. Идеально подходит для создания стильного образа в прохладную погоду.",
    composition: "70% шерсть, 20% полиэстер, 10% кашемир",
    care: "Сухая чистка",
    tryOnImage: "/beige-wool-coat-women-elegant.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
    isSale: true,
  },
  {
    id: 2,
    name: "Платье миди с поясом",
    brand: "LOVE REPUBLIC",
    price: 7990,
    category: "Одежда",
    subcategory: "Платья",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Изумрудный", "Чёрный", "Бордовый"],
    images: ["/emerald-green-midi-dress-elegant.jpg"],
    description:
      "Изящное платье миди с акцентным поясом на талии. Струящаяся ткань красиво драпируется и подчёркивает силуэт.",
    composition: "100% полиэстер",
    care: "Машинная стирка при 30°C",
    tryOnImage: "/emerald-green-midi-dress-elegant.jpg",
    tryOnCategory: "one-pieces",
    tryOnGarmentPhotoType: "model",
    isNew: true,
  },
  {
    id: 3,
    name: "Костюм классический",
    brand: "HENDERSON",
    price: 24990,
    category: "Одежда",
    subcategory: "Костюмы",
    gender: "men",
    sizes: ["46", "48", "50", "52", "54"],
    colors: ["Тёмно-синий", "Чёрный", "Серый"],
    images: ["/dark-blue-business-suit-men.jpg"],
    description: "Классический мужской костюм из итальянской шерсти. Приталенный силуэт, две пуговицы, боковые шлицы.",
    composition: "100% шерсть",
    care: "Сухая чистка",
    tryOnImage: "/dark-blue-business-suit-men.jpg",
    tryOnCategory: "one-pieces",
    tryOnGarmentPhotoType: "model",
  },
  {
    id: 4,
    name: "Джинсы straight fit",
    brand: "LEVI'S",
    price: 9490,
    oldPrice: 12990,
    category: "Одежда",
    subcategory: "Джинсы",
    gender: "unisex",
    sizes: ["26", "27", "28", "29", "30", "31", "32", "33", "34"],
    colors: ["Синий", "Голубой", "Чёрный"],
    images: ["/classic-blue-jeans-straight-fit.jpg"],
    description: "Легендарные джинсы прямого кроя. Плотный деним с эффектом потёртости, классическая посадка на талии.",
    composition: "99% хлопок, 1% эластан",
    care: "Машинная стирка при 40°C",
    tryOnImage: "/classic-blue-jeans-straight-fit.jpg",
    tryOnCategory: "bottoms",
    tryOnGarmentPhotoType: "model",
    isSale: true,
  },
  {
    id: 5,
    name: "Блуза с бантом",
    brand: "SELA",
    price: 3490,
    category: "Одежда",
    subcategory: "Блузы",
    gender: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Белый", "Розовый", "Голубой"],
    images: ["/white-silk-blouse-with-bow.jpg"],
    description: "Нежная блуза с изящным бантом на воротнике. Лёгкая ткань с шелковистой текстурой.",
    composition: "100% полиэстер",
    care: "Ручная стирка",
    tryOnImage: "/white-silk-blouse-with-bow.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
    isNew: true,
  },
  {
    id: 6,
    name: "Куртка кожаная",
    brand: "MANGO",
    price: 15990,
    category: "Одежда",
    subcategory: "Куртки",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Чёрный", "Коричневый"],
    images: ["/black-leather-jacket-women-biker.jpg"],
    description: "Стильная кожаная куртка в байкерском стиле. Асимметричная молния, множество карманов.",
    composition: "Натуральная кожа",
    care: "Специальный уход за кожей",
    tryOnImage: "/black-leather-jacket-women-biker.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
  },
  {
    id: 7,
    name: "Свитер оверсайз",
    brand: "MASSIMO DUTTI",
    price: 8990,
    category: "Одежда",
    subcategory: "Свитеры",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Молочный", "Серый", "Тёмно-зелёный"],
    images: ["/cream-oversized-knit-sweater-cozy.jpg"],
    description: "Уютный свитер оверсайз крупной вязки. Мягкая шерсть с добавлением кашемира.",
    composition: "70% шерсть, 30% кашемир",
    care: "Ручная стирка",
    tryOnImage: "/cream-oversized-knit-sweater-cozy.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
  },
  {
    id: 8,
    name: "Рубашка льняная",
    brand: "TOMMY HILFIGER",
    price: 7990,
    oldPrice: 10990,
    category: "Одежда",
    subcategory: "Рубашки",
    gender: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Белый", "Голубой", "Бежевый"],
    images: ["/light-blue-linen-shirt-men-summer.jpg"],
    description: "Лёгкая льняная рубашка для жаркой погоды. Расслабленный крой, воротник кент.",
    composition: "100% лён",
    care: "Машинная стирка при 40°C",
    tryOnImage: "/light-blue-linen-shirt-men-summer.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
    isSale: true,
  },
  {
    id: 9,
    name: "Юбка плиссе",
    brand: "RESERVED",
    price: 4490,
    category: "Одежда",
    subcategory: "Юбки",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Чёрный", "Бежевый", "Хаки"],
    images: ["/black-pleated-midi-skirt-elegant.jpg"],
    description: "Элегантная юбка-плиссе длины миди. Эластичный пояс для комфортной посадки.",
    composition: "100% полиэстер",
    care: "Машинная стирка при 30°C",
    tryOnImage: "/black-pleated-midi-skirt-elegant.jpg",
    tryOnCategory: "bottoms",
    tryOnGarmentPhotoType: "model",
  },
  {
    id: 10,
    name: "Худи с принтом",
    brand: "NIKE",
    price: 6990,
    category: "Одежда",
    subcategory: "Толстовки",
    gender: "unisex",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Серый", "Чёрный", "Белый"],
    images: ["/grey-nike-hoodie-sporty-streetwear.jpg"],
    description: "Спортивное худи с фирменным логотипом. Мягкий флис внутри, капюшон на шнурке.",
    composition: "80% хлопок, 20% полиэстер",
    care: "Машинная стирка при 30°C",
    tryOnImage: "/grey-nike-hoodie-sporty-streetwear.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
    isNew: true,
  },
  {
    id: 11,
    name: "Брюки wide leg",
    brand: "COS",
    price: 11990,
    category: "Одежда",
    subcategory: "Брюки",
    gender: "women",
    sizes: ["34", "36", "38", "40", "42"],
    colors: ["Чёрный", "Бежевый", "Тёмно-серый"],
    images: ["/black-wide-leg-trousers-women-elegant.jpg"],
    description: "Элегантные брюки с широкими штанинами. Высокая посадка, стрелки спереди.",
    composition: "65% полиэстер, 33% вискоза, 2% эластан",
    care: "Машинная стирка при 30°C",
    tryOnImage: "/black-wide-leg-trousers-women-elegant.jpg",
    tryOnCategory: "bottoms",
    tryOnGarmentPhotoType: "model",
  },
  {
    id: 12,
    name: "Поло классическое",
    brand: "LACOSTE",
    price: 8490,
    category: "Одежда",
    subcategory: "Поло",
    gender: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Белый", "Тёмно-синий", "Зелёный", "Красный"],
    images: ["/navy-blue-lacoste-polo-shirt-men-classic.jpg"],
    description: "Культовое поло Lacoste из хлопкового пике. Приталенный крой, эмблема крокодила.",
    composition: "100% хлопок",
    care: "Машинная стирка при 40°C",
    tryOnImage: "/navy-blue-lacoste-polo-shirt-men-classic.jpg",
    tryOnCategory: "tops",
    tryOnGarmentPhotoType: "model",
  },
]

export const categories = [
  { name: "Женщинам", gender: "women" as const },
  { name: "Мужчинам", gender: "men" as const },
  { name: "Детям", gender: "unisex" as const },
]

export const subcategories = [
  "Пальто",
  "Платья",
  "Костюмы",
  "Джинсы",
  "Блузы",
  "Куртки",
  "Свитеры",
  "Рубашки",
  "Юбки",
  "Толстовки",
  "Брюки",
  "Поло",
]
